Title: Tech notes
author: Ruslan V. Akhpashev #add your own name here

execute:
  execute_notebooks: "off"

only_build_toc_files: true

html:
  favicon : "figures/sibsutis_logo.png"
  baseurl :  "https://sibsutistelecomdep.github.io/blog" #Replace this with your own URL

parse:
  myst_enable_extensions: # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - replacements
    - smartquotes
    - substitution

sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    thebe_config:
      use_thebe_lite: true
      exclude_patterns: ["**/_*.yml", "**/*.md", "**/*.ipynb"]
    html_context:
      default_mode: "light"
    html_theme_options:
      navigation_with_keys: false
      home_page_in_toc: true
      logo:
        text: Tech notes
        image_light: sibsutis_ico.jfif # Put your logo for the light mode here (can be the same as image_dark)
        image_dark: TeachBooks_logo_inverted.svg # Put your logo for the dark mode here (can be the same as image_light)
      repository_url: "https://github.com/sibsutisTelecomDep/blog" #add your own repo URL here
      path_to_docs: "book"
      repository_branch: "main"
      use_edit_page_button: true
      use_repository_button: true
      use_issues_button : true
      html_static_path: ["figures"] # add folders that contain files that need to be included, such as the location of the logo(s)
      show_navbar_depth: 2
      launch_buttons:
        thebe: true
      navbar_start:
        - navbar-logo
      navbar_center:
        - navbar-nav
    html_show_copyright: false
    html_last_updated_fmt: '%B %-d, %Y'
    mathjax3_config:
      chtml: {
        mtextInheritFont: true # To typeset text within math prettier
      }
  extra_extensions:
    - sphinx.ext.imgconverter
    - jupyterbook_patches
    - download_link_replacer
    - sphinx.ext.extlinks
    - sphinx_image_inverter
    - sphinx_iframes
    - sphinx_exercise
    - teachbooks_sphinx_tippy
    - sphinxcontrib.mermaid
    - sphinxcontrib.wavedrom
    - sphinxcontrib.plantuml
    - sphinxcontrib.tikz
    - sphinxcontrib.blockdiag

bibtex_bibfiles: 
  - references.bib
